baseURL = "https://www.ronja-tutorials.com"
languageCode = "en-us"
title = "Portfolio"
theme = "ananke"
assetDir = "static"
# disqusShortname = "ronja-tutorials"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "colorful"
    tabWidth = 2


[params]
	custom_css = ["css/main.css"]